FROM digitalcity-registry.cn-beijing.cr.aliyuncs.com/gdc/nginx:alpine
RUN echo "Asia/shanghai" > /etc/timezone
COPY . /usr/share/nginx/html/gdcd-pro
COPY ./nginx-gdcd-pro.conf /etc/nginx/conf.d/default.conf
EXPOSE 80